controller_manager_ns: ''
controller_list:
  - name: romeo_dcm/RightArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - RShoulderPitch
      - RShoulderYaw
      - RElbowRoll
      - RElbowYaw
      - RWristRoll
      - RWristYaw
  - name: romeo_dcm/LeftArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - LShoulderPitch
      - LShoulderYaw
      - LElbowRoll
      - LElbowYaw
      - LWristRoll
      - LWristYaw
  - name: romeo_dcm/RightHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - RWristPitch
      - RHand
  - name: romeo_dcm/LeftHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - LWristPitch
      - LHand
  - name: romeo_dcm/Torso_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - TrunkYaw
#      - waist
#  - name: romeo_dcm/LeftLeg_controller
#    action_ns: follow_joint_trajectory
#    type: FollowJointTrajectory
#    default: true
#    joints:
#      - LHipYaw
#      - LHipRoll
#      - LHipPitch
#      - LKneePitch
#      - LAnklePitch
#      - LAnkleRoll
# #     - LToePitch
#  - name: romeo_dcm/RightLeg_controller
#    action_ns: follow_joint_trajectory
#    type: FollowJointTrajectory
#    default: true
#    joints:
#      - RHipYaw
#      - RHipRoll
#      - RHipPitch
#      - RKneePitch
#      - RAnklePitch
#      - RAnkleRoll
# #     - RToePitch
  - name: romeo_dcm/Head_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - NeckYaw
      - NeckPitch
      - HeadPitch
      - HeadRoll
